#!/usr/bin/env bash
#shellcheck disable=SC2086
#Script that shows info about subdomain
if (( "$#" == 1 ));
then
    subdom='www lb-01 web-01 web-02'
else
    subdom="$2"
fi
for s in $subdom
do
    echo -n "The subdomain $s"
    dig "$s$1" | awk 'NR == 14 {printf " is a %s record and points to %s\n", $4, $5}'
done
