#!/usr/bin/env bash
#Script that describes the process of install Nginx
if [ ! -x /usr/sbin/nginx ];
then
    sudo apt-get -y update
    sudo apt-get -y install nginx
fi
redirection="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=lmvUFhjZdFc permanent; \n"
sudo sed -i "37i $redirection" /etc/nginx/sites-enabled/default
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
