#!/usr/bin/env bash
#Script that describes the process of install Nginx
sudo apt-get update
sudo apt-get install nginx -y
redirection="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=lmvUFhjZdFc permanent; \n"
not_found="\\\terror_page 404 /custom_404.html;\n\tlocation = custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "37i $redirection" /etc/nginx/sites-enabled/default
sudo sed -i "39i $not_found" /etc/nginx/sites-enabled/default
sudo service nginx restart
