#!/usr/bin/env bash
#Script to debug Nginx at port 80 with no 
chmod 404 /etc/nginx/nginx.conf
sed -i '1,/80/s/80/8080/' /etc/nginx/sites-enabled/default
pkill apache2
chmod 666 /run/nginx.pid
sudo -u nginx service nginx start
